### ISSUE TITLE
Bower should work without CDN

### ISSUE THREAD

**Issue by jrhorn424** [erm0l0v/webpack_examples#2]
I think this is just a typo, but I thought I'd ask here before creating a PR.

https://github.com/erm0l0v/webpack_examples/blob/master/0_simple_ex/ex5_jquery_bower/index.html

This example uses bower, but still links to jquery CDN in the index. This example should work without that, correct?

**Comment by erm0l0v** [comment]
Yes, you're right. It's my mistake and this example will work without link to jQuery CDN.
Thank You!
